### ISSUE TITLE
Bug with checkbox questions

### ISSUE THREAD

**Issue by Hellboy1008** [exlskills/exlskills#18]
"check answer" sometimes returns incorrect even if the user answer is correct. Only after trying to submit the same answer multiple times does "check answer" return correct.

**Comment by svarlamov** [comment]
@stanvarlamov Can you take a look at this? It should be somewhere here...

Request arrives: https://github.com/exlskills/gql-server/blob/master/src/relay-mutations/exam/submit-answer.js#L105

Gets processed: https://github.com/exlskills/gql-server/blob/master/src/relay-mutate-and-get/exam-question-mag.js#L12

I looked at this previously, and it had to do with the ordering in the search... Idk what the problem is now -- or maybe I never fixed it in the first place -- but it's almost certainly nested somewhere in the `src/relay-mutate-and-get/exam-question-mag.js` file where that logic primarily resides

**Comment by stanvarlamov** [comment]
Code had sorting on an undefined parameter, followed by in-sequence ID compare. Updated the code to use the actual ID compare, regardless of the position. Also updated the scoring for multi-choice answers.

**Comment by svarlamov** [comment]
@stanvarlamov Is this in prod? You can always ping @kkhenkina-EXL to have a look and then close this

**Comment by svarlamov** [comment]
@Hellboy1008 Can u check n close today? Thx

**Comment by Hellboy1008** [comment]
Tested the current course and the issue has been solved.
