### ISSUE TITLE
instance.create is called before new workspace for repl

### ISSUE THREAD

**Issue by Hellboy1008** [exlskills/exlskills#19]
![screen shot 2018-08-10 at 3 41 32 pm](https://user-images.githubusercontent.com/21053648/43945186-f94bdb7c-9cb3-11e8-9eed-349f8b422096.png)

**Comment by svarlamov** [comment]
This is a nuanced issue... So technically it is being handled correctly -- although it usually does throw an error -- it catches and retries once the workspace is up. Now, when this issue was posted, WSENV was not working so that's what caused it to not show the code. 

Overall, I think the main thing is that this IDE is never going to be 100% perfect, so I think we need to invest in better error messages to the user, etc.
