### ISSUE TITLE
Paid Sub. "Upgrade Button" Lag

### ISSUE THREAD

**Issue by kkhenkina-EXL** [exlskills/exlskills#38]
**URL:** exlskills,com/learn-en

**Current behavior:** Once a subscription is paid for it does not immediately reflect on the dashboard. Once refreshed, the "Upgrade" button is removed.

**How to Recreate:** Sign up for a subscription and click on "here" to go back to the dashboard on the payment confirmation page.

**What to Fix:** "Upgrade" button availability after subscription is paid.

**Expected Outcome:** Once a sub is paid for and the site is navigated to there should be no "Upgrade" button available.

**Comment by svarlamov** [comment]
So looking at the logs, I can conclude that it almost certainly due to Zoho webhook lag -- not the web client itself... In the logs, there's a roughly 20 second lag between the subscription being created and the webhook call appearing in the logs. I think the only option is likely to add a special flag in the link (or a special URL) that will show a thank you/loading overlay and periodically ping until you are a premium user. @LanderMuruaga Do you know what we are talking about here? I think we would need a quick wireframe and then can implement asap

**Comment by LanderMuruaga** [comment]
I think I understood, but not sure. Please, let me know if this is what you are thinking about...
You can use this overlay window almost everywhere but... Is this the right page to display?
![paid-transition](https://user-images.githubusercontent.com/41282864/44471294-e0325680-a62b-11e8-97d0-efe3a8a77160.png)

**Comment by svarlamov** [comment]
Yeah we'll show something like that on the dashboard then. Makes sense -- thanks @LanderMuruaga

**Comment by svarlamov** [comment]
Updated link in subscriptions system for redirect. This new page is deployed and will wait until the user is upgraded then refresh and go to dashboard -- ensuring that they have premium! 

![image](https://user-images.githubusercontent.com/10859025/44655935-8c5baf00-aa29-11e8-95a3-839ca872a66c.png)
