### ISSUE TITLE
Course sidebar, card nav major UI refactor

### ISSUE THREAD

**Issue by svarlamov** [exlskills/exlskills#59]
Updating the course sidebar and card navigation per the following designs:

### Desktop
![image](https://user-images.githubusercontent.com/10859025/45401262-6b7a9700-b682-11e8-9604-b23fb4da28cf.png)

### Mobile
TODO? @LanderMuruaga 

- [x] Remove old card header

- [x] Add section title to card header

- [x] Add dotnav to card header (also replacing exam nav with this new dotnav since it's a shared component

- [ ] Code logic for card next/previous without questions (this is a bit tricky due to the data that component is missing - but we'll get a solution on this, potentially via the query that the sidebar is using or another GQL query)

- [x] Add course sidebar to card view

- [ ] Refactor sidebar aesthetics

- [ ] Build sidebar support for 2-layers of nested menus (top level, first nested, second nested)

- [x] Design mobile sidebar

- [ ] Update mobile sidebar accordingly

**Comment by svarlamov** [comment]
@LanderMuruaga Can you please send me the colors to use for the dark components:

* Dark sidebar colors

* Dark page background

* Dark content background (i.e., content background)

**Comment by LanderMuruaga** [comment]
Desk & Mobile Logic (responsive):

LEARN
**Desk:** Right sidebar + Moving from Unit to another through dots or Next/Prev. 
**Mobile** no sidebar, only the header Arrow to go back to course + Moving from a Unit to another with arrows. Aditionally I added a dropdown on title to move to other unit/content. It is a power feature. Most users will never discover because they go straight-forward through the guided method (from a Q. to another) but power users or recurrent users will. 

PRACTICE
**Desk**: Lightbox like currently but with content realigned.
**Mobile**: Uses same construc in responsive


![04 - learn course](https://user-images.githubusercontent.com/41282864/45566619-84887100-b857-11e8-9c4b-bdb5a93b10b7.png)
![04c - practice course](https://user-images.githubusercontent.com/41282864/45566620-85210780-b857-11e8-80be-60675bbdc8c4.png)


![m-04-learn course](https://user-images.githubusercontent.com/41282864/45566293-8bfb4a80-b856-11e8-9f19-8984d06cc782.png)
![m-04a-course-nav](https://user-images.githubusercontent.com/41282864/45566294-8bfb4a80-b856-11e8-8250-01b29051f413.png)
![m-04b-practice course](https://user-images.githubusercontent.com/41282864/45566297-8bfb4a80-b856-11e8-9a23-dccf0bde4f9f.png)

**Comment by LanderMuruaga** [comment]
IMPORTANT:
Discussion and updates to this issue have been moved to Issue https://github.com/exlskills/exlskills/issues/76
