### ISSUE TITLE
Live Course design

### ISSUE THREAD

**Issue by LanderMuruaga** [exlskills/exlskills#64]
Design for the different Steps for the LIVE Course

- [x] Course list/grid
![00-courses](https://user-images.githubusercontent.com/41282864/45485047-80285f00-b756-11e8-88cf-21d65ec9355a.png)

- [x] Course page. 
![1 - course detail-b](https://user-images.githubusercontent.com/41282864/45485055-84547c80-b756-11e8-9783-946bd361c6d0.png)

- [x] LIVE Course detail page.
![08-live course](https://user-images.githubusercontent.com/41282864/45565791-05923900-b855-11e8-90f3-4089419ed8b6.png)

**Comment by svarlamov** [comment]
Thanks for posting this  @LanderMuruaga. Adding my comments below:

1) It's unclear in the current UI that the Live course is a sign up for a series of live sessions (basically cohorts) that start on different dates and then follow a schedule. This is because the live courses will have beginning lessons and then progress with the same group of people. So maybe we can update the "Agenda" section to have each row with a "Starts on {{date}}" and then have each one be expandable to show all of the times for the sessions. (Similar to how we have the expandable course unit cards)

2) Consider adding a "Why take a live course" section maybe?

3) I don't currently see any pricing data/options. I assume that this is going to be after they click on the register button?

4) What happens after they click on the register button?

5) I agree on using a full-width banner. I think that we can update the issue to reflect that.

**Comment by LanderMuruaga** [comment]
@svarlamov , looking to it that way it is :) I understood wrong. Hope this solves it... both, Desk + mobile

**Doubts...** 
If Pricing, is same for all courses inside Agenda, it could go on the top highlighted, as a CTA making it more attractive.

**Register** 
After clicking it, it should bring users to payment confirmation and back to the curse.
Once user is registered to a LIVE course, can we show it instead of the Banner on Course detail, telling to the user that he/she has it on X date. Or we can show it on the top also. Is important to communicate it.

![08-live course](https://user-images.githubusercontent.com/41282864/45565791-05923900-b855-11e8-90f3-4089419ed8b6.png)

![m-08-live course](https://user-images.githubusercontent.com/41282864/45580680-43628200-b894-11e8-9c07-e282b2542c95.png)

NOTE: The menu navigates into the course. It is actually the same content than the Left sidebar on desktop.

**Comment by LanderMuruaga** [comment]
I think the only element we are missing here is the banners or adds that link all those pages.
Working on them.

**Comment by svarlamov** [comment]
Closing as irrelevant/fixed due to the migration to spf-server
